### ISSUE TITLE
[Enhancement] Support email and Telegram notifications simultaneously

### ISSUE THREAD

**Issue by TICgal** [pluginsGLPI/telegrambot#6]
Yes, it's on the roadmap, but just to be sure :) 

This plugin is not quite useless until we can choose between email and telegram. Telegram notificacions will be great to cleanup email.

**Comment by wawax** [comment]
Hi,

The notification process is being improved in GLPI 9.2.
It's, IMHO, better to wait a little bit, because this feature request should be covered (not the telegram transport, but the fact to choose it's notification).

**Comment by TICgal** [comment]
Hi @wawax,
Great news.
We'll wait then. Thanks

**Comment by filipemenezes** [comment]
Greate news

**Comment by filipemenezes** [comment]
From the current plugin's version on, it is available.
