### ISSUE TITLE
Messages send only to one recipient instead of few

### ISSUE THREAD

**Issue by freewood** [pluginsGLPI/telegrambot#7]
If message should be send to few techinicians, it's send only to one of them (probably last added, I'm not sure) as a few copies.
At least this happens on "New followup" event, I'm not tested them all.

How to reproduce:

1. Setup telegram notifications to users A and B;
2. Set notification with event "New followup" and recipient "Technician in charge of ticket";
3. Assign users A and B as technicians to the ticket;
4. Leave a new followup in this ticket;
5. User B (or A, but only one of them) will recieve two copies of the notification.

**Comment by Smiley-k** [comment]
Yes, Yes, Yes, I also see this problem

**Comment by brzd-me** [comment]
I noticed that when creating a Comment in the Ticket, the notification is sent to the first registered Telegram user even if he not "Assigned to" in new Ticket!

**Comment by filipemenezes** [comment]
I really appreciate for your help.
The problem has been fixed.
